package com.mchz.nbg.talendservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2016-05-18T14:28:43.017+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://www.talend.com/mdm", name = "TMDMService")
@XmlSeeAlso({ObjectFactory.class})
public interface TMDMService {

    @WebMethod
    @RequestWrapper(localName = "putTransformerV2", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutTransformerV2")
    @ResponseWrapper(localName = "putTransformerV2Response", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutTransformerV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformerV2PK putTransformerV2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutTransformerV2 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getServiceConfiguration", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetServiceConfiguration")
    @ResponseWrapper(localName = "getServiceConfigurationResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetServiceConfigurationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString getServiceConfiguration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSServiceGetConfiguration arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getStoredProcedure", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetStoredProcedure")
    @ResponseWrapper(localName = "getStoredProcedureResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetStoredProcedureResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStoredProcedure getStoredProcedure(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetStoredProcedure arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTransformerPluginV2Configuration", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerPluginV2Configuration")
    @ResponseWrapper(localName = "getTransformerPluginV2ConfigurationResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerPluginV2ConfigurationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString getTransformerPluginV2Configuration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSTransformerPluginV2GetConfiguration arg0
    );

    @WebMethod
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString ping(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPing arg0
    );

    @WebMethod
    @RequestWrapper(localName = "xPathsSearch", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.XPathsSearch")
    @ResponseWrapper(localName = "xPathsSearchResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.XPathsSearchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray xPathsSearch(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSXPathsSearch arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTransformer", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformer")
    @ResponseWrapper(localName = "getTransformerResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformer getTransformer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetTransformer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "executeTransformerV2AsJob", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExecuteTransformerV2AsJob")
    @ResponseWrapper(localName = "executeTransformerV2AsJobResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExecuteTransformerV2AsJobResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBackgroundJobPK executeTransformerV2AsJob(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExecuteTransformerV2AsJob arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRoutingOrderV2PKsByCriteria", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoutingOrderV2PKsByCriteria")
    @ResponseWrapper(localName = "getRoutingOrderV2PKsByCriteriaResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoutingOrderV2PKsByCriteriaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingOrderV2PKArray getRoutingOrderV2PKsByCriteria(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetRoutingOrderV2PKsByCriteria arg0
    );

    @WebMethod
    @RequestWrapper(localName = "extractThroughTransformerV2", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExtractThroughTransformerV2")
    @ResponseWrapper(localName = "extractThroughTransformerV2Response", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExtractThroughTransformerV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformerContext extractThroughTransformerV2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExtractThroughTransformerV2 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMenu", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetMenu")
    @ResponseWrapper(localName = "getMenuResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetMenuResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSMenu getMenu(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetMenu arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putTransformerPluginV2Configuration", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutTransformerPluginV2Configuration")
    @ResponseWrapper(localName = "putTransformerPluginV2ConfigurationResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutTransformerPluginV2ConfigurationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString putTransformerPluginV2Configuration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSTransformerPluginV2PutConfiguration arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsTransformerV2", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsTransformerV2")
    @ResponseWrapper(localName = "existsTransformerV2Response", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsTransformerV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsTransformerV2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsTransformerV2 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getStoredProcedurePKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetStoredProcedurePKs")
    @ResponseWrapper(localName = "getStoredProcedurePKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetStoredProcedurePKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStoredProcedurePKArray getStoredProcedurePKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSRegexStoredProcedure arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putStoredProcedure", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutStoredProcedure")
    @ResponseWrapper(localName = "putStoredProcedureResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutStoredProcedureResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStoredProcedurePK putStoredProcedure(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutStoredProcedure arg0
    );

    @WebMethod
    @RequestWrapper(localName = "removeDroppedItem", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.RemoveDroppedItem")
    @ResponseWrapper(localName = "removeDroppedItemResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.RemoveDroppedItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDroppedItemPK removeDroppedItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSRemoveDroppedItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateDigest", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.UpdateDigest")
    @ResponseWrapper(localName = "updateDigestResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.UpdateDigestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSLong updateDigest(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDigest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "processFileUsingTransformer", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ProcessFileUsingTransformer")
    @ResponseWrapper(localName = "processFileUsingTransformerResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ProcessFileUsingTransformerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSPipeline processFileUsingTransformer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSProcessFileUsingTransformer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "processFileUsingTransformerAsBackgroundJob", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ProcessFileUsingTransformerAsBackgroundJob")
    @ResponseWrapper(localName = "processFileUsingTransformerAsBackgroundJobResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ProcessFileUsingTransformerAsBackgroundJobResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBackgroundJobPK processFileUsingTransformerAsBackgroundJob(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSProcessFileUsingTransformerAsBackgroundJob arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRole", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRole")
    @ResponseWrapper(localName = "getRoleResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRole getRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetRole arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsRoutingRule", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsRoutingRule")
    @ResponseWrapper(localName = "existsRoutingRuleResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsRoutingRuleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsRoutingRule(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsRoutingRule arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRoutingRule", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoutingRule")
    @ResponseWrapper(localName = "getRoutingRuleResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoutingRuleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingRule getRoutingRule(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetRoutingRule arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getDataModelPKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetDataModelPKs")
    @ResponseWrapper(localName = "getDataModelPKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetDataModelPKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDataModelPKArray getDataModelPKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSRegexDataModelPKs arg0
    );

    @WebMethod
    @RequestWrapper(localName = "routingEngineV2Action", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.RoutingEngineV2Action")
    @ResponseWrapper(localName = "routingEngineV2ActionResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.RoutingEngineV2ActionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingEngineV2Status routingEngineV2Action(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSRoutingEngineV2Action arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsView", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsView")
    @ResponseWrapper(localName = "existsViewResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsViewResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsView(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsView arg0
    );

    @WebMethod
    @RequestWrapper(localName = "routeItemV2", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.RouteItemV2")
    @ResponseWrapper(localName = "routeItemV2Response", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.RouteItemV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingRulePKArray routeItemV2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSRouteItemV2 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getBackgroundJob", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetBackgroundJob")
    @ResponseWrapper(localName = "getBackgroundJobResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetBackgroundJobResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBackgroundJob getBackgroundJob(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetBackgroundJob arg0
    );

    @WebMethod
    @RequestWrapper(localName = "serviceAction", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ServiceAction")
    @ResponseWrapper(localName = "serviceActionResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ServiceActionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString serviceAction(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSServiceAction arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAllDroppedItemsPKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.FindAllDroppedItemsPKs")
    @ResponseWrapper(localName = "findAllDroppedItemsPKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.FindAllDroppedItemsPKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDroppedItemPKArray findAllDroppedItemsPKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSFindAllDroppedItemsPKs arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteItem", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteItem")
    @ResponseWrapper(localName = "deleteItemResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPK deleteItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsTransformer", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsTransformer")
    @ResponseWrapper(localName = "existsTransformerResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsTransformerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsTransformer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsTransformer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteStoredProcedure", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteStoredProcedure")
    @ResponseWrapper(localName = "deleteStoredProcedureResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteStoredProcedureResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStoredProcedurePK deleteStoredProcedure(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteStoredProcedure arg0
    );

    @WebMethod
    @RequestWrapper(localName = "updateItemMetadata", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.UpdateItemMetadata")
    @ResponseWrapper(localName = "updateItemMetadataResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.UpdateItemMetadataResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPK updateItemMetadata(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSUpdateMetadataItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putItemWithReportArray", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutItemWithReportArray")
    @ResponseWrapper(localName = "putItemWithReportArrayResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutItemWithReportArrayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPKArray putItemWithReportArray(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutItemWithReportArray arg0
    );

    @WebMethod
    @RequestWrapper(localName = "loadDroppedItem", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.LoadDroppedItem")
    @ResponseWrapper(localName = "loadDroppedItemResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.LoadDroppedItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDroppedItem loadDroppedItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSLoadDroppedItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRoutingRulePKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoutingRulePKs")
    @ResponseWrapper(localName = "getRoutingRulePKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoutingRulePKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingRulePKArray getRoutingRulePKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetRoutingRulePKs arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getDigest", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetDigest")
    @ResponseWrapper(localName = "getDigestResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetDigestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDigest getDigest(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDigestKey arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getItem", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItem")
    @ResponseWrapper(localName = "getItemResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItem getItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "executeRoutingOrderV2Synchronously", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExecuteRoutingOrderV2Synchronously")
    @ResponseWrapper(localName = "executeRoutingOrderV2SynchronouslyResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExecuteRoutingOrderV2SynchronouslyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString executeRoutingOrderV2Synchronously(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExecuteRoutingOrderV2Synchronously arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putItemArray", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutItemArray")
    @ResponseWrapper(localName = "putItemArrayResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutItemArrayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPKArray putItemArray(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutItemArray arg0
    );

    @WebMethod
    @RequestWrapper(localName = "recoverDroppedItem", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.RecoverDroppedItem")
    @ResponseWrapper(localName = "recoverDroppedItemResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.RecoverDroppedItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPK recoverDroppedItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSRecoverDroppedItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getViewPKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetViewPKs")
    @ResponseWrapper(localName = "getViewPKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetViewPKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSViewPKArray getViewPKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetViewPKs arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putDataModel", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutDataModel")
    @ResponseWrapper(localName = "putDataModelResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutDataModelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDataModelPK putDataModel(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutDataModel arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteBusinessConcept", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteBusinessConcept")
    @ResponseWrapper(localName = "deleteBusinessConceptResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteBusinessConceptResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString deleteBusinessConcept(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteBusinessConcept arg0
    );

    @WebMethod
    @RequestWrapper(localName = "runQuery", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.RunQuery")
    @ResponseWrapper(localName = "runQueryResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.RunQueryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray runQuery(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSRunQuery arg0
    );

    @WebMethod
    @RequestWrapper(localName = "extractUsingTransformer", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExtractUsingTransformer")
    @ResponseWrapper(localName = "extractUsingTransformerResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExtractUsingTransformerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSPipeline extractUsingTransformer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExtractUsingTransformer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteTransformerV2", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteTransformerV2")
    @ResponseWrapper(localName = "deleteTransformerV2Response", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteTransformerV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformerV2PK deleteTransformerV2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteTransformerV2 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "checkSchema", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.CheckSchema")
    @ResponseWrapper(localName = "checkSchemaResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.CheckSchemaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString checkSchema(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSCheckSchema arg0
    );

    @WebMethod
    @RequestWrapper(localName = "checkServiceConfiguration", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.CheckServiceConfiguration")
    @ResponseWrapper(localName = "checkServiceConfigurationResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.CheckServiceConfigurationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSCheckServiceConfigResponse checkServiceConfiguration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSCheckServiceConfigRequest arg0
    );

    @WebMethod
    @RequestWrapper(localName = "logout", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.LogoutResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString logout(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSLogout arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getItemsSort", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItemsSort")
    @ResponseWrapper(localName = "getItemsSortResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItemsSortResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray getItemsSort(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetItemsSort arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putTransformer", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutTransformer")
    @ResponseWrapper(localName = "putTransformerResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutTransformerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformerPK putTransformer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutTransformer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getItemPKsByFullCriteria", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItemPKsByFullCriteria")
    @ResponseWrapper(localName = "getItemPKsByFullCriteriaResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItemPKsByFullCriteriaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPKsByCriteriaResponse getItemPKsByFullCriteria(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetItemPKsByFullCriteria arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getDataModel", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetDataModel")
    @ResponseWrapper(localName = "getDataModelResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetDataModelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDataModel getDataModel(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetDataModel arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTransformerPKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerPKs")
    @ResponseWrapper(localName = "getTransformerPKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerPKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformerPKArray getTransformerPKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetTransformerPKs arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsDBDataCluster", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsDBDataCluster")
    @ResponseWrapper(localName = "existsDBDataClusterResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsDBDataClusterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsDBDataCluster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsDBDataCluster arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putItem", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutItem")
    @ResponseWrapper(localName = "putItemResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPK putItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getDataCluster", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetDataCluster")
    @ResponseWrapper(localName = "getDataClusterResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetDataClusterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDataCluster getDataCluster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetDataCluster arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putItemWithReport", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutItemWithReport")
    @ResponseWrapper(localName = "putItemWithReportResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutItemWithReportResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPK putItemWithReport(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutItemWithReport arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteItems", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteItems")
    @ResponseWrapper(localName = "deleteItemsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteItemsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSInt deleteItems(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteItems arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putBusinessConcept", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutBusinessConcept")
    @ResponseWrapper(localName = "putBusinessConceptResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutBusinessConceptResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString putBusinessConcept(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutBusinessConcept arg0
    );

    @WebMethod
    @RequestWrapper(localName = "processBytesUsingTransformer", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ProcessBytesUsingTransformer")
    @ResponseWrapper(localName = "processBytesUsingTransformerResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ProcessBytesUsingTransformerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSPipeline processBytesUsingTransformer(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSProcessBytesUsingTransformer arg0
    );

    @WebMethod
    @RequestWrapper(localName = "executeStoredProcedure", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExecuteStoredProcedure")
    @ResponseWrapper(localName = "executeStoredProcedureResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExecuteStoredProcedureResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray executeStoredProcedure(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExecuteStoredProcedure arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putRole", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutRole")
    @ResponseWrapper(localName = "putRoleResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRolePK putRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutRole arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteDataCluster", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteDataCluster")
    @ResponseWrapper(localName = "deleteDataClusterResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteDataClusterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDataClusterPK deleteDataCluster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteDataCluster arg0
    );

    @WebMethod
    @RequestWrapper(localName = "executeRoutingOrderV2Asynchronously", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExecuteRoutingOrderV2Asynchronously")
    @ResponseWrapper(localName = "executeRoutingOrderV2AsynchronouslyResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExecuteRoutingOrderV2AsynchronouslyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingOrderV2PK executeRoutingOrderV2Asynchronously(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExecuteRoutingOrderV2Asynchronously arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getItemPKsByCriteria", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItemPKsByCriteria")
    @ResponseWrapper(localName = "getItemPKsByCriteriaResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItemPKsByCriteriaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPKsByCriteriaResponse getItemPKsByCriteria(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetItemPKsByCriteria arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTransformerPluginV2Details", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerPluginV2Details")
    @ResponseWrapper(localName = "getTransformerPluginV2DetailsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerPluginV2DetailsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformerPluginV2Details getTransformerPluginV2Details(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetTransformerPluginV2Details arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putItemWithCustomReport", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutItemWithCustomReport")
    @ResponseWrapper(localName = "putItemWithCustomReportResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutItemWithCustomReportResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPK putItemWithCustomReport(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutItemWithCustomReport arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getItemsByCustomFKFilters", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItemsByCustomFKFilters")
    @ResponseWrapper(localName = "getItemsByCustomFKFiltersResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItemsByCustomFKFiltersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray getItemsByCustomFKFilters(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetItemsByCustomFKFilters arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getConceptsInDataCluster", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetConceptsInDataCluster")
    @ResponseWrapper(localName = "getConceptsInDataClusterResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetConceptsInDataClusterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray getConceptsInDataCluster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetConceptsInDataCluster arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteDataModel", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteDataModel")
    @ResponseWrapper(localName = "deleteDataModelResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteDataModelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDataModelPK deleteDataModel(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteDataModel arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteView", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteView")
    @ResponseWrapper(localName = "deleteViewResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteViewResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSViewPK deleteView(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteView arg0
    );

    @WebMethod
    @RequestWrapper(localName = "executeTransformerV2", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExecuteTransformerV2")
    @ResponseWrapper(localName = "executeTransformerV2Response", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExecuteTransformerV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformerContext executeTransformerV2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExecuteTransformerV2 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "isItemModifiedByOther", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.IsItemModifiedByOther")
    @ResponseWrapper(localName = "isItemModifiedByOtherResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.IsItemModifiedByOtherResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean isItemModifiedByOther(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSIsItemModifiedByOther arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getBusinessConcepts", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetBusinessConcepts")
    @ResponseWrapper(localName = "getBusinessConceptsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetBusinessConceptsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray getBusinessConcepts(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetBusinessConcepts arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsDataModel", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsDataModel")
    @ResponseWrapper(localName = "existsDataModelResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsDataModelResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsDataModel(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsDataModel arg0
    );

    @WebMethod
    @RequestWrapper(localName = "checkFKIntegrity", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.CheckFKIntegrity")
    @ResponseWrapper(localName = "checkFKIntegrityResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.CheckFKIntegrityResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.FkIntegrityCheckResult checkFKIntegrity(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRoutingOrderV2ByCriteriaWithPaging", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoutingOrderV2ByCriteriaWithPaging")
    @ResponseWrapper(localName = "getRoutingOrderV2ByCriteriaWithPagingResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoutingOrderV2ByCriteriaWithPagingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingOrderV2Array getRoutingOrderV2ByCriteriaWithPaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetRoutingOrderV2ByCriteriaWithPaging arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTransformerPluginV2SList", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerPluginV2SList")
    @ResponseWrapper(localName = "getTransformerPluginV2SListResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerPluginV2SListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformerPluginV2SList getTransformerPluginV2SList(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetTransformerPluginV2SList arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteRole", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteRole")
    @ResponseWrapper(localName = "deleteRoleResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRolePK deleteRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteRole arg0
    );

    @WebMethod
    @RequestWrapper(localName = "isPagingAccurate", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.IsPagingAccurate")
    @ResponseWrapper(localName = "isPagingAccurateResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.IsPagingAccurateResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean isPagingAccurate(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSInt arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putMenu", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutMenu")
    @ResponseWrapper(localName = "putMenuResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutMenuResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSMenuPK putMenu(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutMenu arg0
    );

    @WebMethod
    @RequestWrapper(localName = "extractUsingTransformerThruView", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExtractUsingTransformerThruView")
    @ResponseWrapper(localName = "extractUsingTransformerThruViewResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExtractUsingTransformerThruViewResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSPipeline extractUsingTransformerThruView(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExtractUsingTransformerThruView arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMDMJob", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetMDMJob")
    @ResponseWrapper(localName = "getMDMJobResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetMDMJobResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSMDMJobArray getMDMJob(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSMDMNULL arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putDataCluster", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutDataCluster")
    @ResponseWrapper(localName = "putDataClusterResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutDataClusterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDataClusterPK putDataCluster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutDataCluster arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putServiceConfiguration", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutServiceConfiguration")
    @ResponseWrapper(localName = "putServiceConfigurationResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutServiceConfigurationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString putServiceConfiguration(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSServicePutConfiguration arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getServicesList", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetServicesList")
    @ResponseWrapper(localName = "getServicesListResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetServicesListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSServicesList getServicesList(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetServicesList arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getBusinessConceptKey", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetBusinessConceptKey")
    @ResponseWrapper(localName = "getBusinessConceptKeyResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetBusinessConceptKeyResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSConceptKey getBusinessConceptKey(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetBusinessConceptKey arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findBackgroundJobPKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.FindBackgroundJobPKs")
    @ResponseWrapper(localName = "findBackgroundJobPKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.FindBackgroundJobPKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBackgroundJobPKArray findBackgroundJobPKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSFindBackgroundJobPKs arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteRoutingRule", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteRoutingRule")
    @ResponseWrapper(localName = "deleteRoutingRuleResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteRoutingRuleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingRulePK deleteRoutingRule(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteRoutingRule arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putBusinessConceptSchema", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutBusinessConceptSchema")
    @ResponseWrapper(localName = "putBusinessConceptSchemaResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutBusinessConceptSchemaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString putBusinessConceptSchema(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutBusinessConceptSchema arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteRoutingOrderV2", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteRoutingOrderV2")
    @ResponseWrapper(localName = "deleteRoutingOrderV2Response", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteRoutingOrderV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingOrderV2PK deleteRoutingOrderV2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteRoutingOrderV2 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getDataClusterPKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetDataClusterPKs")
    @ResponseWrapper(localName = "getDataClusterPKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetDataClusterPKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDataClusterPKArray getDataClusterPKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSRegexDataClusterPKs arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTransformerV2PKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerV2PKs")
    @ResponseWrapper(localName = "getTransformerV2PKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerV2PKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformerV2PKArray getTransformerV2PKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetTransformerV2PKs arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getFullPathValues", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetFullPathValues")
    @ResponseWrapper(localName = "getFullPathValuesResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetFullPathValuesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray getFullPathValues(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetFullPathValues arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAutoIncrement", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetAutoIncrement")
    @ResponseWrapper(localName = "getAutoIncrementResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetAutoIncrementResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSAutoIncrement getAutoIncrement(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSAutoIncrement arg0
    );

    @WebMethod
    @RequestWrapper(localName = "viewSearch", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ViewSearch")
    @ResponseWrapper(localName = "viewSearchResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ViewSearchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray viewSearch(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSViewSearch arg0
    );

    @WebMethod
    @RequestWrapper(localName = "processBytesUsingTransformerAsBackgroundJob", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ProcessBytesUsingTransformerAsBackgroundJob")
    @ResponseWrapper(localName = "processBytesUsingTransformerAsBackgroundJobResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ProcessBytesUsingTransformerAsBackgroundJobResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBackgroundJobPK processBytesUsingTransformerAsBackgroundJob(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSProcessBytesUsingTransformerAsBackgroundJob arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteMenu", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteMenu")
    @ResponseWrapper(localName = "deleteMenuResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteMenuResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSMenuPK deleteMenu(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteMenu arg0
    );

    @WebMethod
    @RequestWrapper(localName = "deleteItemWithReport", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteItemWithReport")
    @ResponseWrapper(localName = "deleteItemWithReportResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DeleteItemWithReportResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString deleteItemWithReport(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDeleteItemWithReport arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsTransformerPluginV2", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsTransformerPluginV2")
    @ResponseWrapper(localName = "existsTransformerPluginV2Response", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsTransformerPluginV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsTransformerPluginV2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsTransformerPluginV2 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getView", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetView")
    @ResponseWrapper(localName = "getViewResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetViewResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSView getView(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetView arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsMenu", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsMenu")
    @ResponseWrapper(localName = "existsMenuResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsMenuResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsMenu(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsMenu arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getComponentVersion", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetComponentVersion")
    @ResponseWrapper(localName = "getComponentVersionResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetComponentVersionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSVersion getComponentVersion(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetComponentVersion arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getBusinessConceptValue", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetBusinessConceptValue")
    @ResponseWrapper(localName = "getBusinessConceptValueResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetBusinessConceptValueResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString getBusinessConceptValue(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetBusinessConceptValue arg0
    );

    @WebMethod
    @RequestWrapper(localName = "partialPutItem", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PartialPutItem")
    @ResponseWrapper(localName = "partialPutItemResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PartialPutItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSItemPK partialPutItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPartialPutItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putRoutingRule", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutRoutingRule")
    @ResponseWrapper(localName = "putRoutingRuleResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutRoutingRuleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingRulePK putRoutingRule(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutRoutingRule arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRoutingOrderV2SByCriteria", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoutingOrderV2SByCriteria")
    @ResponseWrapper(localName = "getRoutingOrderV2SByCriteriaResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRoutingOrderV2SByCriteriaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRoutingOrderV2Array getRoutingOrderV2SByCriteria(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetRoutingOrderV2SByCriteria arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMDMConfiguration", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetMDMConfiguration")
    @ResponseWrapper(localName = "getMDMConfigurationResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetMDMConfigurationResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSMDMConfig getMDMConfiguration();

    @WebMethod
    @RequestWrapper(localName = "dropItem", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DropItem")
    @ResponseWrapper(localName = "dropItemResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.DropItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSDroppedItemPK dropItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDropItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getItems", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItems")
    @ResponseWrapper(localName = "getItemsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetItemsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray getItems(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetItems arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMenuPKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetMenuPKs")
    @ResponseWrapper(localName = "getMenuPKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetMenuPKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSMenuPKArray getMenuPKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetMenuPKs arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putDBDataCluster", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutDBDataCluster")
    @ResponseWrapper(localName = "putDBDataClusterResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutDBDataClusterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean putDBDataCluster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutDBDataCluster arg0
    );

    @WebMethod
    @RequestWrapper(localName = "supportStaging", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.SupportStaging")
    @ResponseWrapper(localName = "supportStagingResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.SupportStagingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean supportStaging(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSDataClusterPK arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getTransformerV2", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerV2")
    @ResponseWrapper(localName = "getTransformerV2Response", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetTransformerV2Response")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSTransformerV2 getTransformerV2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetTransformerV2 arg0
    );

    @WebMethod
    @RequestWrapper(localName = "count", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.Count")
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.CountResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString count(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSCount arg0
    );

    @WebMethod
    @RequestWrapper(localName = "countItemsByCustomFKFilters", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.CountItemsByCustomFKFilters")
    @ResponseWrapper(localName = "countItemsByCustomFKFiltersResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.CountItemsByCustomFKFiltersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSString countItemsByCustomFKFilters(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSCountItemsByCustomFKFilters arg0
    );

    @WebMethod
    @RequestWrapper(localName = "initMDM", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.InitMDM")
    @ResponseWrapper(localName = "initMDMResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.InitMDMResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSInt initMDM(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSInitData arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getServiceDocument", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetServiceDocument")
    @ResponseWrapper(localName = "getServiceDocumentResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetServiceDocumentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSServiceGetDocument getServiceDocument(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSString arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsDataCluster", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsDataCluster")
    @ResponseWrapper(localName = "existsDataClusterResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsDataClusterResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsDataCluster(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsDataCluster arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putBackgroundJob", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutBackgroundJob")
    @ResponseWrapper(localName = "putBackgroundJobResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutBackgroundJobResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBackgroundJobPK putBackgroundJob(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutBackgroundJob arg0
    );

    @WebMethod
    @RequestWrapper(localName = "putView", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutView")
    @ResponseWrapper(localName = "putViewResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.PutViewResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSViewPK putView(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSPutView arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsStoredProcedure", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsStoredProcedure")
    @ResponseWrapper(localName = "existsStoredProcedureResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsStoredProcedureResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsStoredProcedure(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsStoredProcedure arg0
    );

    @WebMethod
    @RequestWrapper(localName = "quickSearch", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.QuickSearch")
    @ResponseWrapper(localName = "quickSearchResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.QuickSearchResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSStringArray quickSearch(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSQuickSearch arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getMDMCategory", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetMDMCategory")
    @ResponseWrapper(localName = "getMDMCategoryResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetMDMCategoryResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSCategoryData getMDMCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSCategoryData arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getRolePKs", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRolePKs")
    @ResponseWrapper(localName = "getRolePKsResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.GetRolePKsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSRolePKArray getRolePKs(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSGetRolePKs arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsItem", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsItem")
    @ResponseWrapper(localName = "existsItemResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsItemResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsItem(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsItem arg0
    );

    @WebMethod
    @RequestWrapper(localName = "existsRole", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsRole")
    @ResponseWrapper(localName = "existsRoleResponse", targetNamespace = "http://www.talend.com/mdm", className = "com.mchz.nbg.talendservice.ExistsRoleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.mchz.nbg.talendservice.WSBoolean existsRole(
        @WebParam(name = "arg0", targetNamespace = "")
        com.mchz.nbg.talendservice.WSExistsRole arg0
    );
}
