#%RAML 0.8
title: nbg_mdm_esb API
version: v1.0
baseUri: http://nbgsynMdm/api/v1.0
/trans:
  displayName: talend use it to synchronize data
  get:
    description: get method to trans
    queryParameters:
      jsonstr:
        type: string
        required: true
        description:  input jsonstr
        example: |
         {"action":"TRANSFOR","operand":"MD_LOCATION_PORT","token":"token","type":"C","applyData":[{"PORT_ID":"346","PORT_CODE":"LTD","PORT_ENAME":"DUTCHHARBOUR","PORT_CNAME":"鹿特丹","PORT_COUNTRY_CODE":"NL","PORT_ACTIVE_FLAG":"Y","PORT_CN_FLAG":"XF"}]}
    responses: 
       200:
        body:
          application/json:
            example: |
              { "msgID":"000","msgDesc":"操作成功","result":""}
  post:
    description: post method to trans
    queryParameters:
      jsonstr:
        type: string
        required: true
        description:  input jsonstr
        example: |
          {"action":"TRANSFOR","operand":"MD_LOCATION_PORT","token":"token","type":"C","applyData":[{"PORT_ID":"346","PORT_CODE":"LTD","PORT_ENAME":"DUTCHHARBOUR","PORT_CNAME":"鹿特丹","PORT_COUNTRY_CODE":"NL","PORT_ACTIVE_FLAG":"Y","PORT_CN_FLAG":"XF"}]}
    responses: 
       200:
        body:
          application/json:
            example: |
              { "msgID":"000","msgDesc":"操作成功","result":""}
      
    