#%RAML 0.8
---
title: hz_bicycle_esb API
version: v1.0
baseUri: http://hz_bicycle_esb/api
mediaType: application/json
schemas:
  - gettest: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "flag" : {
            "type" : "string"
          }
        }    
      }
  - getstationall: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "day" : {
            "type" : "string"
          },
          "cost" : {
            "type" : "integer"
          }
          
        }      
      }      
documentation:
  - title: Introduction
    content: |
      API to manage the .
resourceTypes: 
  - base:
      get:
        responses:
          200:
            body:
              schema: get<<resourcePathName>> # e.g. get-auth
  - collection:
      description: Collection of available <<resourcePathName>>.
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                example: |
                  <<exampleCollection>>
      post:
        description: | 
            Add a new <<resourcePathName|!singularize>> .
        body:
          application/json:
            schema: <<resourcePathName|!singularize>>
            example: |
              <<exampleItem>>
        responses:
          200:
            body:
              application/json:
                example: |
                  { "message": "The <<resourcePathName|!singularize>> has been properly entered" }
traits:
  - searchable:
      queryParameters:
        query:
          description: |
            JSON  {"field1":"value1",...,"fieldN":"valueN"} <<description>>
          example: |
            <<example>>
/test:
  type: base
  get:
    is: [searchable: {description: "with valid searchable fields: username, password", example: "{\"username\": \"admin\",\"password\": \"123\"}"}]
    responses:
      200:
        body:
          example: |
            {
                "flag" : "111"
            }
/stationall:
  type: base
  get:
    is: [searchable: {description: "with valid searchable fields: pname", example: "{\"pname\": \"wang\"}"}]
    description: |
          全部站点.
    responses:
      200:
        body:
          example: |
            {
              "day" : "2",
              "cost" : 100
            }   